version: '3.7'
services:
    backend:
        build: .
        environment:
          - PORT=8080
          - MAX_WORKERS=1
        restart: always
        ports:
            - "8088:8080"
            